server {
  listen 80;
  server_name _;
  resolver 127.0.0.11 ipv6=off valid=30s;

  root /usr/share/nginx/html;
  index index.html;

  location = /bakeryFlow {
    return 301 /bakeryFlow/;
  }

  location /bakeryFlow/api/ {
    proxy_pass http://bakeryflow-backend:8086/api/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Prefix /bakeryFlow/api;
  }

  location /bakeryFlow/ {
    proxy_pass http://bakeryflow-frontend:8085/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
